apiVersion: stack.zncdata.net/v1alpha1
kind: Airbyte
metadata:
  labels:
    app.kubernetes.io/name: airbyte
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/part-of: airbyte-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: airbyte-operator
  name: airbyte
spec:
  global:
    serviceAccountName: airbyte-admin
    logs:
      externalMinio:
        enabled: true
        host: "192.168.9.30"
        port: 31826
      s3:
        enabled: false
        bucket: "airbyte-dev-logs"
  server:
    enabled: true
    replicas: 1
    image:
      repository: airbyte/server
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      port: 8001
      type: ClusterIP
  worker:
    enabled: true
    debug: true
    image:
      repository: airbyte/worker
      tag: 0.50.30
      pullPolicy: IfNotPresent
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  airbyteApiServer:
    enabled: false
    image:
      repository: airbyte/airbyte-api-server
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    replicas: 1
    service:
      port: 80
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  airbyteBootloader:
    enabled: true
    image:
      repository: airbyte/airbyte-bootloader
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  connectorBuilderServer:
    enabled: true
    image:
      repository: airbyte/connector-builder-server
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      port: 80
  keycloak:
    enabled: false
    image:
      repository: airbyte/keycloak
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  postgres:
    host: "192.168.9.30"
    port: "31011"
    username: "airbyte"
    password: "airbyte"
    database: "db-airbyte"
  temporal:
    enabled: false
    image:
      repository: temporalio/auto-setup
      tag: 1.20.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      port: 7233
  webApp:
    enabled: true
    image:
      repository: airbyte/webapp
      tag: 0.50.30
      pullPolicy: IfNotPresent
    service:
      port: 80
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  cron:
    enabled: true
    replicas: 1
    image:
      repository: airbyte/cron
      tag: 0.50.30
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  podSweeper:
    enabled: true
    replicas: 1
    image:
      repository: bitnami/kubectl
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi